# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Persist Waka Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run persist
        env:
          WAKATIME_URL: ${{ secrets.WAKATIME_URL }}
          WAKA_API_KEY: ${{ secrets.WAKA_API_KEY }}
          DB_ADDRESS: ${{ secrets.DB_ADDRESS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_COLL: ${{ secrets.DB_COLL }}
